version: 2
project_name: bash-language-server

archives:
  - id: default
    ids:
      - default
    format_overrides:
      - goos: windows
        formats:
          - zip
    formats: [tar.gz]
    strip_binary_directory: true

builds:
  - id: default
    builder: bun
    command: build
    dir: server
    main: ./out/cli.js
    binary: bash-language-server
    targets:
      - linux-x64
      - linux-arm64
      - darwin-x64
      - darwin-arm64
      - windows-x64
    hooks:
      pre:
        - bun install
        - bun run compile
        - bun run build:bundle
