name: Verify changes

on: [pull_request]

jobs:
  verify:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Install shellcheck and shfmt (used for testing)
        run: sudo apt-get install -y shellcheck shfmt

      - uses: oven-sh/setup-bun@v2
        with:
          cache: true

      - run: bun install

      - name: Verify changes
        run: bun run verify:bail
